# Generated by Django 4.0 on 2021-12-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
    ]
